name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "needs-triage", "type: bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Thanks for reporting a bug!

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Clear description of the bug
      placeholder: "Describe the bug..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How to trigger the bug
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened
      placeholder: "What should happen?"
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, browser, Node.js version, etc.
      placeholder: "e.g., Ubuntu 22.04, Chrome 120, Node.js 18"

  - type: textarea
    id: additional
    attributes:
      label: Additional info
      description: Screenshots, error logs, etc.
      placeholder: "Any additional context..."
