name: Release from Changelog

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - 'CHANGELOG.md'
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release (optional)'
        required: false

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Determine tag
        id: tag
        run: |
          if [ -n "${{ github.event.inputs.tag }}" ]; then
            echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
            exit 0
          fi
          # For tag push events
          if [[ "${GITHUB_REF:-}" == refs/tags/* ]]; then
            ref=${GITHUB_REF#refs/tags/}
            echo "tag=${ref}" >> $GITHUB_OUTPUT
            exit 0
          fi
          # For main pushes, read package.json
          VERSION=$(node -p "require('./package.json').version")
          echo "tag=v${VERSION}" >> $GITHUB_OUTPUT

      - name: Create or update release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          TAG=${{ steps.tag.outputs.tag }}
          echo "Creating release for $TAG"
          node scripts/create-release.mjs
