name: Test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    
    strategy:
      matrix:
        bun-version: [latest]
        
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}
          
      - name: Install dependencies
        run: bun install
        
      - name: Run tests
        run: bun run test